In [2]:
import pandas as pd

In [4]:
import os
print(os.getcwd())

c:\Users\omala\OneDrive\Documenti\Project1_procurement-fraud-detection\notebooks

In [5]:
print(os.listdir("../archive"))

['Procument Invoice Fraud Dataset v1']

In [6]:
invoices = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/invoices.parquet")

In [7]:
invoices.head()

,invoice_id,supplier_id,department_id,invoice_date,invoice_amount,currency,payment_terms,invoice_type,submission_hour,image_path
0,INV_0000000,7316ce64-2a14-4a96-9b0c-62eb27c8fc6c,DPT_025,2023-04-18,3565.57,ZAR,NET60,GOODS,18,data/v1/20251214_172643/images/INV_0000000.png
1,INV_0000001,7428a656-b3ee-4d3b-9a10-412954aebd1b,DPT_010,2023-10-08,9871.78,ZAR,NET30,SERVICES,6,NaN
2,INV_0000002,7b0ccad9-eee1-4cae-b02e-21aa352b6ec8,DPT_041,2023-09-24,8530.64,ZAR,NET60,SERVICES,23,NaN
3,INV_0000003,1c6345ab-6e0e-41e8-985d-3f861d2324e6,DPT_015,2023-10-15,1378.52,ZAR,NET30,GOODS,7,NaN
4,INV_0000004,22d839d3-33e4-4986-b18c-ccdc131eb723,DPT_039,2023-06-07,2373.66,ZAR,NET30,GOODS,12,NaN

In [8]:
invoices.shape

(300000, 10)

In [9]:
invoices.columns

Index(['invoice_id', 'supplier_id', 'department_id', 'invoice_date',
       'invoice_amount', 'currency', 'payment_terms', 'invoice_type',
       'submission_hour', 'image_path'],
      dtype='str')

In [10]:
invoices.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   invoice_id       300000 non-null  str
 1   supplier_id      300000 non-null  str
 2   department_id    300000 non-null  str
 3   invoice_date     300000 non-null  datetime64[ns]
 4   invoice_amount   300000 non-null  float64
 5   currency         300000 non-null  str
 6   payment_terms    300000 non-null  str
 7   invoice_type     300000 non-null  str
 8   submission_hour  300000 non-null  int64
 9   image_path       45000 non-null   str
dtypes: datetime64[ns](1), float64(1), int64(1), str(7)
memory usage: 44.5 MB

In [11]:
print(os.listdir("../archive/Procument Invoice Fraud Dataset v1"))

['behavioural_features.parquet', 'departments.parquet', 'images', 'images_metadata.parquet', 'invoices.parquet', 'labels.parquet', 'manifest.json', 'splits.parquet', 'suppliers.parquet']

In [12]:
labels = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/labels.parquet")

In [13]:
labels.head()

    invoice_id  is_fraud fraud_type fraud_tags          explanations
0  INV_0000000         0       NONE               {"reason": "NONE"}
1  INV_0000001         0       NONE               {"reason": "NONE"}
2  INV_0000002         0       NONE               {"reason": "NONE"}
3  INV_0000003         1      SPLIT      SPLIT  {"rules": ["SPLIT"]}
4  INV_0000004         0       NONE               {"reason": "NONE"}

In [14]:
labels["is_fraud"].value_counts()

is_fraud
0    233590
1     66410
Name: count, dtype: int64

In [15]:
labels["is_fraud"].value_counts(normalize=True) * 100

is_fraud
0    77.863333
1    22.136667
Name: proportion, dtype: float64

In [16]:
labels["fraud_type"].value_counts()

fraud_type
NONE              237036
SPLIT              42346
GHOST_SUPPLIER     12588
INFLATED            5581
DOC_TAMPER          2379
DUPLICATE             70
Name: count, dtype: int64

In [17]:
pd.crosstab(labels["is_fraud"], labels["fraud_type"])

fraud_type  DOC_TAMPER  DUPLICATE  GHOST_SUPPLIER  INFLATED    NONE  SPLIT
is_fraud
0                   49          0             244       115  232313    869
1                 2330         70           12344      5466    4723  41477

In [18]:
import json

with open("../archive/Procument Invoice Fraud Dataset v1/manifest.json", "r") as file:
    manifest = json.load(file)

manifest

{'version': 'v1',
 'generated_utc': '20251214_172643',
 'counts': {'suppliers': 2000,
  'departments': 50,
  'invoices': 300000,
  'behavioural_features': 300000,
  'labels': 300000,
  'images': 45000},
 'format': 'parquet'}

In [23]:
suppliers = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/suppliers.parquet")
suppliers.head()

,supplier_id,supplier_country,supplier_age_days,supplier_risk_score,blacklisted_flag,avg_invoice_amount
0,fc3e058b-e0f3-4ab0-9cec-4eb5edd96831,SV,841,0.244,0,5590.25
1,3d4cbf37-4eb9-4eff-8e88-cb2dd4e80839,KE,61,0.284,0,5797.64
2,913e4de2-e0c5-4cb8-bda9-c2a90ed42f1a,YE,197,0.390,0,897.65
3,bb5e4bcf-15ed-4269-9429-6c07f26b4776,SA,851,0.299,0,7727.71
4,fa5d3100-11b7-4948-90e6-e6607c69dee1,DJ,4373,0.418,0,5458.67

In [24]:
suppliers.shape

(2000, 6)

In [25]:
suppliers.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   supplier_id          2000 non-null   str
 1   supplier_country     2000 non-null   str
 2   supplier_age_days    2000 non-null   int64
 3   supplier_risk_score  2000 non-null   float64
 4   blacklisted_flag     2000 non-null   int64
 5   avg_invoice_amount   2000 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 168.1 KB

In [27]:
behaviour = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/behavioural_features.parquet")
behaviour.head()

,invoice_id,supplier_invoice_count_30d,supplier_avg_amount_90d,invoice_amount_zscore,duplicate_invoice_flag,split_invoice_flag,late_night_submission_flag
0,INV_0138003,1.0,4252.160000,-0.375908,0,0,0
1,INV_0153155,2.0,13972.275000,1.830169,0,0,0
2,INV_0034829,3.0,17737.206667,2.008863,0,0,0
3,INV_0072998,4.0,14480.340000,-0.323982,0,1,0
4,INV_0211525,5.0,12515.048000,-0.330321,0,1,0

In [28]:
behaviour.shape

(300000, 7)

In [29]:
behaviour.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 7 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   invoice_id                  300000 non-null  str
 1   supplier_invoice_count_30d  300000 non-null  float64
 2   supplier_avg_amount_90d     300000 non-null  float64
 3   invoice_amount_zscore       300000 non-null  float64
 4   duplicate_invoice_flag      300000 non-null  int64
 5   split_invoice_flag          300000 non-null  int64
 6   late_night_submission_flag  300000 non-null  int64
dtypes: float64(3), int64(3), str(1)
memory usage: 19.2 MB

In [30]:
pd.crosstab(
    behaviour["split_invoice_flag"],
    labels["fraud_type"]
)

fraud_type,DOC_TAMPER,DUPLICATE,GHOST_SUPPLIER,INFLATED,NONE,SPLIT
split_invoice_flag,,,,,,
0,2029,63,10749,4799,203303,36378
1,350,7,1839,782,33733,5968

In [32]:
behaviour_labels = behaviour.merge(labels, on="invoice_id")
behaviour_labels.shape

(300000, 11)

In [33]:
pd.crosstab(
    behaviour_labels["split_invoice_flag"],
    behaviour_labels["fraud_type"]
)

fraud_type,DOC_TAMPER,DUPLICATE,GHOST_SUPPLIER,INFLATED,NONE,SPLIT
split_invoice_flag,,,,,,
0,2054,62,12588,5581,237036,0
1,325,8,0,0,0,42346

In [34]:
pd.crosstab(
    behaviour_labels["duplicate_invoice_flag"],
    behaviour_labels["fraud_type"]
)

fraud_type,DOC_TAMPER,DUPLICATE,GHOST_SUPPLIER,INFLATED,NONE,SPLIT
duplicate_invoice_flag,,,,,,
0,2379,0,12588,5581,237036,42346
1,0,70,0,0,0,0

In [35]:
pd.crosstab(
    behaviour_labels["late_night_submission_flag"],
    behaviour_labels["fraud_type"]
)

fraud_type,DOC_TAMPER,DUPLICATE,GHOST_SUPPLIER,INFLATED,NONE,SPLIT
late_night_submission_flag,,,,,,
0,0,53,9515,4266,179044,31958
1,2379,17,3073,1315,57992,10388

In [36]:
behaviour[
    ["supplier_invoice_count_30d", "supplier_avg_amount_90d", "invoice_amount_zscore"]
].describe()

,supplier_invoice_count_30d,supplier_avg_amount_90d,invoice_amount_zscore
count,300000.000000,300000.000000,3.000000e+05
mean,12.635893,7572.864589,5.835924e-17
std,3.918758,6240.050468,1.000002e+00
min,1.000000,193.330000,-8.542044e-01
25%,10.000000,3654.072531,-5.586563e-01
50%,13.000000,5767.308586,-3.032648e-01
75%,15.000000,9358.080053,1.817357e-01
max,31.000000,294048.720000,3.251019e+01

In [37]:
behaviour_labels.groupby("fraud_type")["invoice_amount_zscore"].mean()

fraud_type
DOC_TAMPER        0.120010
DUPLICATE        -0.365467
GHOST_SUPPLIER    0.025025
INFLATED          4.829157
NONE             -0.015811
SPLIT            -0.561531
Name: invoice_amount_zscore, dtype: float64

In [38]:
behaviour_labels.groupby("fraud_type")["invoice_amount_zscore"].describe()

,count,mean,std,min,25%,50%,75%,max
fraud_type,,,,,,,,
DOC_TAMPER,2379.0,0.120010,1.248795,-0.827889,-0.556041,-0.289844,0.253961,14.851054
DUPLICATE,70.0,-0.365467,0.625041,-0.801975,-0.719636,-0.574028,-0.329359,2.148827
GHOST_SUPPLIER,12588.0,0.025025,0.708004,-0.840584,-0.464670,-0.207219,0.278993,2.999807
INFLATED,5581.0,4.829157,2.277333,3.001025,3.444005,4.079076,5.344173,32.510194
NONE,237036.0,-0.015811,0.695382,-0.842324,-0.503718,-0.237980,0.238844,2.999620
SPLIT,42346.0,-0.561531,0.256211,-0.854204,-0.722385,-0.635278,-0.489157,3.020892

In [39]:
behaviour_labels.groupby("fraud_type")["supplier_invoice_count_30d"].mean()

fraud_type
DOC_TAMPER        12.880622
DUPLICATE         12.014286
GHOST_SUPPLIER    12.753257
INFLATED          12.585917
NONE              12.575883
SPLIT             12.930784
Name: supplier_invoice_count_30d, dtype: float64

In [40]:
behaviour_labels.groupby("fraud_type")["supplier_avg_amount_90d"].mean()

fraud_type
DOC_TAMPER         8839.521104
DUPLICATE          4744.668999
GHOST_SUPPLIER     7561.078345
INFLATED          25695.999722
NONE               7112.508680
SPLIT              7698.228708
Name: supplier_avg_amount_90d, dtype: float64

In [41]:
departments = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/departments.parquet")

departments.head()

  department_id        region  annual_budget
0       DPT_000  Rhode Island   3.278881e+08
1       DPT_001      Arkansas   2.666879e+07
2       DPT_002        Nevada   1.491465e+07
3       DPT_003      New York   4.204102e+08
4       DPT_004     Louisiana   2.956358e+08

In [42]:
departments.shape

(50, 3)

In [44]:
departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  50 non-null     str
 1   region         50 non-null     str
 2   annual_budget  50 non-null     float64
dtypes: float64(1), str(2)
memory usage: 2.1 KB

In [45]:
splits = pd.read_parquet("../archive/Procument Invoice Fraud Dataset v1/splits.parquet")

splits.head()

    invoice_id  split
0  INV_0258729  train
1  INV_0179434  train
2  INV_0123072  train
3  INV_0031388  train
4  INV_0205955  train

In [46]:
splits.shape

(300000, 2)

In [47]:
splits.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   invoice_id  300000 non-null  str
 1   split       300000 non-null  str
dtypes: str(2)
memory usage: 9.0 MB

In [48]:
splits["split"].value_counts()

split
train    210000
test      60000
val       30000
Name: count, dtype: int64